[features]
seeds = false
[programs.localnet]
sol_did = "didso1Dpqpm4CsiCjzP766BGY89CAdD6ZBL68cRhFPc"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./tests/fixtures/A2oYuurjzc8ACwQQN56SBLv1kUmYJJTBjwMNWVNgVaT3.json"

[scripts]
createTestFixtureAccount = "ts-node ./scripts/createTestFixtureAccount"
